version: "3.8"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./public:/usr/src/app/public
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://root:example@mongo:27017/campus_lost_found?authSource=admin
      - JWT_SECRET=your_jwt_secret_here
      - OTP_DEFAULT=TRUE
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  mongo:
    image: mongo:5.0
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')" -u root -p example
      interval: 10s
      timeout: 30s
      retries: 3
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongo_data:
